name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        type: string
  
permissions: 
  packages: write

jobs:
  publish: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Wiki.js repository
        uses: actions/checkout@v4
        with:
          repository: requarks/wiki
          ref: refs/tags/${{ inputs.version }}
          path: wikijs
      
      - run: |
          cd wikijs    
          for patch in ../patches/*.patch; do
            echo "Applying $patch"
            git apply "$patch"
          done
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/build-push-action@v6
        with:
          context: wikijs
          push: true
          tags: |
            ghcr.io/teamwolfyta/wikijs-test:${{ inputs.version }}
            ghcr.io/teamwolfyta/wikijs-test:latest
          file: dev/build/Dockerfile